version: '3.8'

services:
  clockr-api:
    image: kornkalle/clockr-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  clockr-app:
    build: ./
    ports:
      - "80:80"
    env_file:
      - .env

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
